# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1303, 708)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_design = QtWidgets.QWidget(Dialog)
        self.widget_design.setStyleSheet("\n"
"   QWidget{\n"
"    background-color: rgb(33, 37, 43);\n"
"    color: rgb(208, 208, 208);\n"
"    font-size: 10pt;\n"
"}\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
" QScrollBar {\n"
"border: none;                                                /* без границ */\n"
"    border-right:5px solid rgb(211, 211, 211);;    /* С правой красной раницей */\n"
" }\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/* Ползунок */\n"
" QScrollBar::handle:vertical {    \n"
"    background:rgb(255, 255, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
"/*Нижняя стрелка*/\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"/*Верхняя стрелка*/\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"/* Цвета нижних и верхних стрелок */\n"
" QScrollBar::up-arrow:vertical{\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     background: rgb(255, 255, 255);\n"
" }\n"
"QScrollBar::down-arrow:vertical{\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     background: rgb(255, 255, 255);\n"
"}\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"RadioButton */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(255, 255, 255);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"/* срабатывает, когда пользователь наводит на элемент мышью */\n"
"QRadioButton:hover {\n"
"    background-color:rgb(40, 44, 52);            /* задаем цвет фона */\n"
"}\n"
"/* срабатывает, при нажатии*/\n"
"QRadioButton:pressed      {\n"
"    background-color:rgb(170, 170, 170);        /* задаем цвет фона */\n"
"    color:  rgb(0, 0, 0);\n"
"    border: none;                                                /* без границ */\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QCheckBox */\n"
"/* Стандартное состояние*/\n"
"QCheckBox{\n"
"    padding-left: 8px;        /* Отступ слева */\n"
"    padding-right: -8px;    /* Отступ справа */\n"
"}\n"
"\n"
"/* Состояние - не выбран*/\n"
"QCheckBox::indicator:unchecked {\n"
"    /* Выбор картинки*/\n"
"    image: url(:/checkbox_status_success/resource/checkbox_status_success/check_error_red_24dp.svg)\n"
"}\n"
"\n"
"/* Состояние -  выбран*/\n"
"QCheckBox::indicator:checked {\n"
"    /* Выбор картинки*/\n"
"    image: url(:/checkbox_status_success/resource/checkbox_status_success/check_ok_grean_24dp.svg);\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QPushButton */\n"
"/*Стандартное состояние для кнопки*/\n"
"QPushButton {\n"
"    font-size: 12pt;\n"
"    background-color:rgb(37, 41, 48);/* задает цвет фона */\n"
"    display: inline-block;                            /* пределяет, будет ли элемент обрабатываться как блочный или встроенный элемент */\n"
"    border: 1px solid rgb(52, 59, 72);        /* задает границу элемента */\n"
"\n"
"    /* задает иконку */\n"
"    background-position: left center;                            /* выравнивание иконки */\n"
"    background-repeat: no-repeat;                                /* повторять иконку */\n"
"} \n"
"\n"
"/* срабатывает, когда пользователь наводит на элемент мышью */\n"
"QPushButton:hover {\n"
"    background-color:rgb(40, 44, 52);            /* задаем цвет фона */\n"
"    border: none;                                                /* без границ */\n"
"    border-left:4px solid rgb(208, 208, 208);    /* С правой красной раницей */\n"
"}\n"
"\n"
"\n"
"/* срабатывает, при нажатии*/\n"
"QPushButton:pressed      {\n"
"    background-color:rgb(170, 170, 170);        /* задаем цвет фона */\n"
"    color: rgb(181, 181, 181);\n"
"    border: none;                                                /* без границ */\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QLineEdit */\n"
"/* Стиль по умолчанию */\n"
"QLineEdit:enabled{\n"
"    background-color:rgb(44, 49, 58); /* Устанавливаем цвет заливки */\n"
"    border: 1px solid rgb(255, 255, 255); \n"
"}\n"
"\n"
"/* Если поле отключено */\n"
"QLineEdit:disabled {\n"
"    background-color:  rgba(67, 74, 88, 0); /* Устанавливаем цвет заливки */\n"
"    border: 1px solid rgb(255, 255, 255); \n"
"    color: rgb(67, 74, 88);\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QGroupBox */\n"
"QGroupBox{\n"
"    color:rgb(255, 255, 255);    /* задает цвет шрифта */\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QTableWidget */\n"
"\n"
"QTableWidget {    \n"
"    gridline-color: rgb(136, 136, 136);\n"
"    border-top: 1px solid rgb(54, 60, 74);\n"
"    border-bottom: 1px solid  rgb(54, 60, 74);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(72, 81, 94);\n"
"}\n"
"QHeaderView { qproperty-defaultAlignment: AlignCenter; }\n"
"/*Цвет верхнего и левого поля*/\n"
"QHeaderView::section{\n"
"    background-color:rgb(37, 41, 48);\n"
"    border-style: none;\n"
"border: 1px solid rgb(136, 136, 136);\n"
"}\n"
"/*Кнопка в верхнем левом углу*/\n"
"QTableCornerButton::section {background-color:rgb(33, 37, 43); }\n"
"\n"
"QWidget#widget_loading_data {\n"
"    border-bottom: 2px solid rgb(208, 208, 208);\n"
"}\n"
"QWidget#widget_processing {\n"
"    border-top: 2px solid rgb(208, 208, 208);\n"
"}\n"
"QScrollArea{\n"
"border: none;\n"
"}")
        self.widget_design.setObjectName("widget_design")
        self.layout_design = QtWidgets.QHBoxLayout(self.widget_design)
        self.layout_design.setContentsMargins(0, 0, 0, 0)
        self.layout_design.setSpacing(3)
        self.layout_design.setObjectName("layout_design")
        self.widget_menu = QtWidgets.QWidget(self.widget_design)
        self.widget_menu.setMinimumSize(QtCore.QSize(240, 0))
        self.widget_menu.setMaximumSize(QtCore.QSize(240, 16777215))
        self.widget_menu.setObjectName("widget_menu")
        self.layout_menu = QtWidgets.QVBoxLayout(self.widget_menu)
        self.layout_menu.setContentsMargins(0, 0, 0, 6)
        self.layout_menu.setSpacing(6)
        self.layout_menu.setObjectName("layout_menu")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_menu)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 240, 634))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, -1, 3, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_antennas = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_antennas.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_antennas.setCheckable(True)
        self.pushButton_antennas.setChecked(True)
        self.pushButton_antennas.setObjectName("pushButton_antennas")
        self.verticalLayout_2.addWidget(self.pushButton_antennas)
        self.widget_antennas = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_antennas.setStyleSheet("")
        self.widget_antennas.setObjectName("widget_antennas")
        self.layout_antennas = QtWidgets.QVBoxLayout(self.widget_antennas)
        self.layout_antennas.setContentsMargins(0, 0, 0, 5)
        self.layout_antennas.setSpacing(2)
        self.layout_antennas.setObjectName("layout_antennas")
        self.groupBox_number_cells_of_antenna_field = QtWidgets.QGroupBox(self.widget_antennas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_number_cells_of_antenna_field.sizePolicy().hasHeightForWidth())
        self.groupBox_number_cells_of_antenna_field.setSizePolicy(sizePolicy)
        self.groupBox_number_cells_of_antenna_field.setFlat(False)
        self.groupBox_number_cells_of_antenna_field.setObjectName("groupBox_number_cells_of_antenna_field")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_number_cells_of_antenna_field)
        self.horizontalLayout_3.setContentsMargins(9, 0, 9, 9)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_text_number_cells_of_antenna_field = QtWidgets.QLabel(self.groupBox_number_cells_of_antenna_field)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_text_number_cells_of_antenna_field.setFont(font)
        self.label_text_number_cells_of_antenna_field.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_number_cells_of_antenna_field.setObjectName("label_text_number_cells_of_antenna_field")
        self.horizontalLayout_3.addWidget(self.label_text_number_cells_of_antenna_field)
        self.lineEdit_number_cells_of_antenna_field = QtWidgets.QLineEdit(self.groupBox_number_cells_of_antenna_field)
        self.lineEdit_number_cells_of_antenna_field.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_number_cells_of_antenna_field.setObjectName("lineEdit_number_cells_of_antenna_field")
        self.horizontalLayout_3.addWidget(self.lineEdit_number_cells_of_antenna_field)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.layout_antennas.addWidget(self.groupBox_number_cells_of_antenna_field)
        self.groupBox_radius_of_cells_of_antenna_field = QtWidgets.QGroupBox(self.widget_antennas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_radius_of_cells_of_antenna_field.sizePolicy().hasHeightForWidth())
        self.groupBox_radius_of_cells_of_antenna_field.setSizePolicy(sizePolicy)
        self.groupBox_radius_of_cells_of_antenna_field.setFlat(False)
        self.groupBox_radius_of_cells_of_antenna_field.setObjectName("groupBox_radius_of_cells_of_antenna_field")
        self.layout_radius_of_cells_of_antenna_field = QtWidgets.QHBoxLayout(self.groupBox_radius_of_cells_of_antenna_field)
        self.layout_radius_of_cells_of_antenna_field.setContentsMargins(9, 0, 9, 9)
        self.layout_radius_of_cells_of_antenna_field.setSpacing(5)
        self.layout_radius_of_cells_of_antenna_field.setObjectName("layout_radius_of_cells_of_antenna_field")
        self.label_text_radius_of_cells_of_antenna_field = QtWidgets.QLabel(self.groupBox_radius_of_cells_of_antenna_field)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_text_radius_of_cells_of_antenna_field.setFont(font)
        self.label_text_radius_of_cells_of_antenna_field.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_radius_of_cells_of_antenna_field.setObjectName("label_text_radius_of_cells_of_antenna_field")
        self.layout_radius_of_cells_of_antenna_field.addWidget(self.label_text_radius_of_cells_of_antenna_field)
        self.lineEdit_radius_of_cells_of_antenna_field = QtWidgets.QLineEdit(self.groupBox_radius_of_cells_of_antenna_field)
        self.lineEdit_radius_of_cells_of_antenna_field.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_radius_of_cells_of_antenna_field.setObjectName("lineEdit_radius_of_cells_of_antenna_field")
        self.layout_radius_of_cells_of_antenna_field.addWidget(self.lineEdit_radius_of_cells_of_antenna_field)
        self.layout_radius_of_cells_of_antenna_field.setStretch(0, 1)
        self.layout_radius_of_cells_of_antenna_field.setStretch(1, 1)
        self.layout_antennas.addWidget(self.groupBox_radius_of_cells_of_antenna_field)
        self.verticalLayout_2.addWidget(self.widget_antennas)
        self.pushButton_antennas_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_antennas_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_antennas_2.setCheckable(True)
        self.pushButton_antennas_2.setChecked(True)
        self.pushButton_antennas_2.setObjectName("pushButton_antennas_2")
        self.verticalLayout_2.addWidget(self.pushButton_antennas_2)
        self.widget_intensity = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_intensity.setStyleSheet("")
        self.widget_intensity.setObjectName("widget_intensity")
        self.layout_intensity = QtWidgets.QVBoxLayout(self.widget_intensity)
        self.layout_intensity.setContentsMargins(0, 0, 0, 5)
        self.layout_intensity.setSpacing(2)
        self.layout_intensity.setObjectName("layout_intensity")
        self.groupBox_number_cells_of_intensity = QtWidgets.QGroupBox(self.widget_intensity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_number_cells_of_intensity.sizePolicy().hasHeightForWidth())
        self.groupBox_number_cells_of_intensity.setSizePolicy(sizePolicy)
        self.groupBox_number_cells_of_intensity.setFlat(False)
        self.groupBox_number_cells_of_intensity.setObjectName("groupBox_number_cells_of_intensity")
        self.layout_number_cells_of_intensity = QtWidgets.QHBoxLayout(self.groupBox_number_cells_of_intensity)
        self.layout_number_cells_of_intensity.setContentsMargins(9, 0, 9, 9)
        self.layout_number_cells_of_intensity.setSpacing(5)
        self.layout_number_cells_of_intensity.setObjectName("layout_number_cells_of_intensity")
        self.label_text_number_cells_of_intensity = QtWidgets.QLabel(self.groupBox_number_cells_of_intensity)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_text_number_cells_of_intensity.setFont(font)
        self.label_text_number_cells_of_intensity.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_number_cells_of_intensity.setObjectName("label_text_number_cells_of_intensity")
        self.layout_number_cells_of_intensity.addWidget(self.label_text_number_cells_of_intensity)
        self.lineEdit_number_cells_of_intensity = QtWidgets.QLineEdit(self.groupBox_number_cells_of_intensity)
        self.lineEdit_number_cells_of_intensity.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_number_cells_of_intensity.setObjectName("lineEdit_number_cells_of_intensity")
        self.layout_number_cells_of_intensity.addWidget(self.lineEdit_number_cells_of_intensity)
        self.layout_number_cells_of_intensity.setStretch(0, 1)
        self.layout_number_cells_of_intensity.setStretch(1, 1)
        self.layout_intensity.addWidget(self.groupBox_number_cells_of_intensity)
        self.groupBox_radius_of_cells_of_intensity = QtWidgets.QGroupBox(self.widget_intensity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_radius_of_cells_of_intensity.sizePolicy().hasHeightForWidth())
        self.groupBox_radius_of_cells_of_intensity.setSizePolicy(sizePolicy)
        self.groupBox_radius_of_cells_of_intensity.setFlat(False)
        self.groupBox_radius_of_cells_of_intensity.setObjectName("groupBox_radius_of_cells_of_intensity")
        self.layout_radius_of_cells_of_intensity = QtWidgets.QHBoxLayout(self.groupBox_radius_of_cells_of_intensity)
        self.layout_radius_of_cells_of_intensity.setContentsMargins(9, 0, 9, 9)
        self.layout_radius_of_cells_of_intensity.setSpacing(5)
        self.layout_radius_of_cells_of_intensity.setObjectName("layout_radius_of_cells_of_intensity")
        self.label_text_radius_of_cells_of_intensity = QtWidgets.QLabel(self.groupBox_radius_of_cells_of_intensity)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_text_radius_of_cells_of_intensity.setFont(font)
        self.label_text_radius_of_cells_of_intensity.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_radius_of_cells_of_intensity.setObjectName("label_text_radius_of_cells_of_intensity")
        self.layout_radius_of_cells_of_intensity.addWidget(self.label_text_radius_of_cells_of_intensity)
        self.lineEdit_radius_of_cells_of_intensity = QtWidgets.QLineEdit(self.groupBox_radius_of_cells_of_intensity)
        self.lineEdit_radius_of_cells_of_intensity.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_radius_of_cells_of_intensity.setObjectName("lineEdit_radius_of_cells_of_intensity")
        self.layout_radius_of_cells_of_intensity.addWidget(self.lineEdit_radius_of_cells_of_intensity)
        self.layout_radius_of_cells_of_intensity.setStretch(0, 1)
        self.layout_radius_of_cells_of_intensity.setStretch(1, 1)
        self.layout_intensity.addWidget(self.groupBox_radius_of_cells_of_intensity)
        self.verticalLayout_2.addWidget(self.widget_intensity)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.layout_menu.addWidget(self.scrollArea)
        self.widget_processing = QtWidgets.QWidget(self.widget_menu)
        self.widget_processing.setObjectName("widget_processing")
        self.layout_processing = QtWidgets.QVBoxLayout(self.widget_processing)
        self.layout_processing.setContentsMargins(0, 2, 0, 0)
        self.layout_processing.setSpacing(0)
        self.layout_processing.setObjectName("layout_processing")
        self.pushButton_display_antenna_installation_field = QtWidgets.QPushButton(self.widget_processing)
        self.pushButton_display_antenna_installation_field.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_display_antenna_installation_field.setObjectName("pushButton_display_antenna_installation_field")
        self.layout_processing.addWidget(self.pushButton_display_antenna_installation_field)
        self.pushButton_start_processing = QtWidgets.QPushButton(self.widget_processing)
        self.pushButton_start_processing.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_start_processing.setObjectName("pushButton_start_processing")
        self.layout_processing.addWidget(self.pushButton_start_processing)
        self.layout_menu.addWidget(self.widget_processing)
        self.layout_design.addWidget(self.widget_menu)
        self.widget_main = QtWidgets.QWidget(self.widget_design)
        self.widget_main.setStyleSheet("QWidget{\n"
"background-color: rgb(240, 240, 240);\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.widget_main.setObjectName("widget_main")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_main)
        self.gridLayout.setContentsMargins(9, 0, -1, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_plot_2 = QtWidgets.QWidget(self.widget_main)
        self.widget_plot_2.setObjectName("widget_plot_2")
        self.layout_plot_2 = QtWidgets.QVBoxLayout(self.widget_plot_2)
        self.layout_plot_2.setContentsMargins(0, 0, 0, 0)
        self.layout_plot_2.setSpacing(0)
        self.layout_plot_2.setObjectName("layout_plot_2")
        self.gridLayout.addWidget(self.widget_plot_2, 0, 1, 1, 1)
        self.widget_plot_3 = QtWidgets.QWidget(self.widget_main)
        self.widget_plot_3.setObjectName("widget_plot_3")
        self.layout_plot_3 = QtWidgets.QVBoxLayout(self.widget_plot_3)
        self.layout_plot_3.setContentsMargins(0, 0, 0, 0)
        self.layout_plot_3.setSpacing(0)
        self.layout_plot_3.setObjectName("layout_plot_3")
        self.gridLayout.addWidget(self.widget_plot_3, 1, 1, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.widget_main)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 518, 708))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_plot_1 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_plot_1.setObjectName("widget_plot_1")
        self.horizontalLayout_2.addWidget(self.widget_plot_1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea_2, 0, 0, 2, 1)
        self.gridLayout.setColumnMinimumWidth(0, 1)
        self.gridLayout.setColumnMinimumWidth(1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.layout_design.addWidget(self.widget_main)
        self.layout_design.setStretch(0, 1)
        self.layout_design.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.widget_design)

        self.retranslateUi(Dialog)
        self.pushButton_antennas.clicked['bool'].connect(self.widget_antennas.setVisible) # type: ignore
        self.pushButton_antennas_2.clicked['bool'].connect(self.widget_intensity.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Интенсивность антен"))
        self.pushButton_antennas.setText(_translate("Dialog", "Область Антенн"))
        self.groupBox_number_cells_of_antenna_field.setTitle(_translate("Dialog", "Кол-во ячеек на радиус"))
        self.label_text_number_cells_of_antenna_field.setText(_translate("Dialog", "R [ шт. ]"))
        self.lineEdit_number_cells_of_antenna_field.setText(_translate("Dialog", "2"))
        self.groupBox_radius_of_cells_of_antenna_field.setTitle(_translate("Dialog", "Значение радиуса граицы"))
        self.label_text_radius_of_cells_of_antenna_field.setText(_translate("Dialog", "R [ ед. ]"))
        self.lineEdit_radius_of_cells_of_antenna_field.setText(_translate("Dialog", "10.0"))
        self.pushButton_antennas_2.setText(_translate("Dialog", "Диаграмма направленности"))
        self.groupBox_number_cells_of_intensity.setTitle(_translate("Dialog", "Кол-во ячеек на радиус"))
        self.label_text_number_cells_of_intensity.setText(_translate("Dialog", "R [ шт. ]"))
        self.lineEdit_number_cells_of_intensity.setText(_translate("Dialog", "60"))
        self.groupBox_radius_of_cells_of_intensity.setTitle(_translate("Dialog", "Значение радиуса граицы"))
        self.label_text_radius_of_cells_of_intensity.setText(_translate("Dialog", "R [ ед. ]"))
        self.lineEdit_radius_of_cells_of_intensity.setText(_translate("Dialog", "100.0"))
        self.pushButton_display_antenna_installation_field.setText(_translate("Dialog", "Обновить поле ввода антен"))
        self.pushButton_start_processing.setText(_translate("Dialog", "Обработка"))
